services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.2.1_v2.0.12-ls459
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Sofia
    volumes:
      - /opt/appdata/qbittorrent:/config
      - /storage:/storage
    ports:
      - 8080:8080
    restart: unless-stopped